import { useCallback, useEffect, useRef, useState } from 'react';
import { invokeAdminFunction } from '../lib/adminApi';
import '../../styles/admin-photos.css';

type Photo = {id:string;vehicle:string;status:string;original_url:string|null;candidate_url:string|null;candidate_bytes:number;candidate_verified:boolean;error?:string;detection:{detected?:boolean;format?:string}};
type Listing = {items:Photo[];counts:Record<string,number>;usedBytes:number;budgetBytes:number;processingEnabled:boolean;registeredVehicles:number;publishedVehicles:number};
const labels:Record<string,string>={queued:'排队中',processing:'处理中',pending_review:'修复待审',needs_inspection:'仅压缩，需检查',approved:'已通过',rejected:'已拒绝',failed:'失败',capacity_blocked:'容量暂停'};
const api=<T,>(action:string,body:Record<string,unknown>={})=>invokeAdminFunction<T>('japan-photo-review',{action,...body});
export function AdminPhotos(){
 const [data,setData]=useState<Listing|null>(null),[filter,setFilter]=useState('pending_review'),[size,setSize]=useState(50),[offset,setOffset]=useState(0),[selected,setSelected]=useState<Set<string>>(new Set()),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[zoom,setZoom]=useState<Photo|null>(null),[decision,setDecision]=useState<string|null>(null),[ack,setAck]=useState(false);
 const sequence=useRef(0);
 const load=useCallback(async()=>{const request=++sequence.current;setBusy(true);setError('');try{const result=await api<Listing>('list',{status:filter,pageSize:size,offset});if(request===sequence.current){setData(result);setSelected(new Set());}}catch(e){if(request===sequence.current)setError(e instanceof Error?e.message:'读取失败');}finally{if(request===sequence.current)setBusy(false);}},[filter,size,offset]);
 useEffect(()=>{void load();const currentSequence=sequence;return()=>{currentSequence.current++;};},[load]);
 const toggle=(id:string)=>setSelected(previous=>{const next=new Set(previous);if(next.has(id))next.delete(id);else next.add(id);return next;});
 const eligible=(p:Photo)=>['pending_review','needs_inspection','approved','rejected'].includes(p.status);
 const chosen=data?.items.filter(p=>selected.has(p.id))||[];
 const run=async(action:string,body:Record<string,unknown>,message:string)=>{setBusy(true);setError('');try{await api(action,body);setDecision(null);setNotice(message);await load();}catch(e){setError(e instanceof Error?e.message:'操作失败');setBusy(false);}};
 const count=filter?(data?.counts[filter]||0):Object.values(data?.counts||{}).reduce((a,b)=>a+b,0);
 return <section className="photo-admin"><h1>图片处理与自动上架</h1><p>云端处理已有库存，电脑关闭也能继续。修补和压缩不调用大模型。车辆全部照片通过审核后进入可上架状态；公开入口等待恢复确认。</p>
 {error&&<p role="alert" className="photo-error">{error}</p>}{notice&&<p role="status">{notice}</p>}
 <div className="photo-stats"><strong>{data?.processingEnabled?'云端处理已开启':'云端处理已暂停'}</strong><span>已登记 {data?.registeredVehicles??0} 辆 · 可上架 {data?.publishedVehicles??0} 辆</span><span>预留 {((data?.usedBytes||0)/1e9).toFixed(2)} / {((data?.budgetBytes||0)/1e9).toFixed(1)} GB</span></div>
 <p>{Object.entries(data?.counts||{}).map(([key,value])=>`${labels[key]||key} ${value}`).join(' · ')}</p>
 <div className="photo-controls"><button disabled={busy||!data} onClick={()=>void run('control',{enabled:!data?.processingEnabled},data?.processingEnabled?'已暂停领取新图片，正在处理的图片会完成。':'已继续，云端工作程序会在下一轮领取任务。')}>{data?.processingEnabled?'暂停处理':'继续处理'}</button><button disabled={busy} onClick={()=>void run('retry',{},'失败任务已重新排队。')}>重试失败项</button><button disabled={busy} onClick={()=>void load()}>刷新进度</button><a href="https://github.com/Chi1111111/innogroup-site/actions/workflows/japan-photo-process.yml" target="_blank" rel="noreferrer">云端运行日志</a></div>
 <p>任务按计划分批运行，刷新可查看最新进度。通过审核的成品验证成功后，云端程序会删除对应原图；容量显示为保守预留量。拒绝任意照片会使对应车辆停止上架；已签发的图片链接最长一小时失效。</p>
 <div className="photo-controls"><select aria-label="图片状态" disabled={busy} value={filter} onChange={e=>{setFilter(e.target.value);setOffset(0);}}><option value="">全部状态</option>{Object.entries(labels).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select><select aria-label="每页数量" disabled={busy} value={size} onChange={e=>{setSize(Number(e.target.value));setOffset(0);}}>{[20,50,100].map(n=><option key={n} value={n}>每页 {n} 张</option>)}</select></div>
 <div className="photo-grid">{data?.items.map(p=><article key={p.id}><label><input type="checkbox" checked={selected.has(p.id)} disabled={busy||!eligible(p)} onChange={()=>toggle(p.id)}/>{p.vehicle}</label><small>{labels[p.status]} · {Math.round(p.candidate_bytes/1000)} KB</small><button className="photo-pair" onClick={()=>setZoom(p)} aria-label={`对比 ${p.vehicle}`}><span>{p.original_url?<img loading="lazy" src={p.original_url} alt="原图"/>:'原图已清理或尚未上传'}<small>原图</small></span><span>{p.candidate_url?<img loading="lazy" src={p.candidate_url} alt="成品"/>:'暂无成品'}<small>{p.detection?.detected?'修补结果':'仅压缩，需检查水印'}</small></span></button>{p.error&&<p className="photo-error">{p.error}</p>}</article>)}</div>
 {!busy&&data?.items.length===0&&<p>当前没有此状态的照片。</p>}
 <div className="photo-controls"><button disabled={busy||offset===0} onClick={()=>setOffset(Math.max(0,offset-size))}>上一页</button><span>第 {offset/size+1} 页 · 共 {count} 张</span><button disabled={busy||offset+size>=count} onClick={()=>setOffset(offset+size)}>下一页</button></div>
 <div className="photo-bulk"><button disabled={busy} onClick={()=>setSelected(new Set(data?.items.filter(eligible).map(p=>p.id)))}>本页全选</button><button disabled={busy} onClick={()=>setSelected(new Set())}>取消全选</button><strong>已选 {selected.size} 张</strong><button disabled={busy||!chosen.length||chosen.some(p=>!p.candidate_url||!p.candidate_verified)} onClick={()=>{setDecision('approved');setAck(false);}}>批量通过</button><button disabled={busy||!chosen.length} onClick={()=>{setDecision('rejected');setAck(false);}}>批量拒绝</button></div>
 {zoom&&<div className="photo-overlay"><div role="dialog" aria-modal="true" aria-label="图片对比" className="photo-dialog"><button onClick={()=>setZoom(null)}>关闭</button><h2>{zoom.vehicle}</h2><div className="photo-pair">{zoom.original_url&&<img src={zoom.original_url} alt="原图"/>}{zoom.candidate_url&&<img src={zoom.candidate_url} alt="成品"/>}</div><div className="photo-controls"><button disabled={data?.items[0]?.id===zoom.id} onClick={()=>{const i=data!.items.findIndex(p=>p.id===zoom.id);setZoom(data!.items[i-1]);}}>上一张</button><button disabled={!eligible(zoom)||busy} onClick={()=>toggle(zoom.id)}>{selected.has(zoom.id)?'取消选择':'选择此图'}</button><button disabled={data?.items.at(-1)?.id===zoom.id} onClick={()=>{const i=data!.items.findIndex(p=>p.id===zoom.id);setZoom(data!.items[i+1]);}}>下一张</button></div></div></div>}
 {decision&&<div className="photo-overlay"><div role="dialog" aria-modal="true" aria-label="确认批量审核" className="photo-dialog small"><h2>{decision==='approved'?'通过':'拒绝'} {selected.size} 张照片</h2><p>车辆全部照片通过后进入可上架状态。目前公开入口保持关闭。</p><label><input type="checkbox" checked={ack} disabled={busy} onChange={e=>setAck(e.target.checked)}/>{decision==='approved'?'我已检查成品，确认无残留水印且未影响车辆信息，并确认可以公开展示。':'确认拒绝这些照片，并停止展示受影响的车辆。'}</label>{error&&<p role="alert">{error}</p>}<div className="photo-controls"><button disabled={busy} onClick={()=>setDecision(null)}>取消</button><button disabled={!ack||busy} onClick={()=>void run('decide-batch',{ids:[...selected],decision},'审核已保存，车辆就绪状态已更新。')}>{busy?'正在保存…':'确认'}</button></div></div></div>}
 </section>;
}
