import { useCallback, useEffect, useRef, useState } from 'react';
import { invokeAdminFunction } from '../lib/adminApi';
import '../../styles/admin-photos.css';

type Photo = {id:string;vehicle:string;status:string;original_url:string|null;candidate_url:string|null;candidate_bytes:number;candidate_verified:boolean;error?:string;detection:{detected?:boolean;format?:string}};
type Listing = {sourceAssignment?:{splitEnabled:boolean;windowsSeenAt:string|null;macSeenAt:string|null};workerSeenAt?:string|null;items:Photo[];counts:Record<string,number>;usedBytes:number;budgetBytes:number;processingEnabled:boolean;registeredVehicles:number;publishedVehicles:number};
const labels:Record<string,string>={queued:'排队中',processing:'处理中',pending_review:'请检查修补效果',needs_inspection:'疑似水印，需检查',approved:'已通过',rejected:'已拒绝',failed:'失败',capacity_blocked:'容量暂停'};
const api=<T,>(action:string,body:Record<string,unknown>={})=>invokeAdminFunction<T>('japan-photo-review',{action,...body});
export function AdminPhotos(){
 const filter='pending_review';
 const [data,setData]=useState<Listing|null>(null),[size,setSize]=useState(20),[offset,setOffset]=useState(0),[selected,setSelected]=useState<Set<string>>(new Set()),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[zoom,setZoom]=useState<Photo|null>(null),[decision,setDecision]=useState<string|null>(null),[ack,setAck]=useState(false);
 const sequence=useRef(0);
 const load=useCallback(async()=>{const request=++sequence.current;setBusy(true);setError('');try{const result=await api<Listing>('list',{status:filter,pageSize:size,offset});if(request===sequence.current){setData(result);setSelected(new Set());}}catch(e){if(request===sequence.current)setError(e instanceof Error?e.message:'读取失败');}finally{if(request===sequence.current)setBusy(false);}},[filter,size,offset]);
 useEffect(()=>{void load();const currentSequence=sequence;return()=>{currentSequence.current++;};},[load]);
 const toggle=(id:string)=>setSelected(previous=>{const next=new Set(previous);if(next.has(id))next.delete(id);else next.add(id);return next;});
 const eligible=(p:Photo)=>['pending_review','needs_inspection','approved','rejected'].includes(p.status);
 const chosen=data?.items.filter(p=>selected.has(p.id))||[];
 const run=async(action:string,body:Record<string,unknown>,message:string)=>{setBusy(true);setError('');try{await api(action,body);setDecision(null);setNotice(message);await load();}catch(e){setError(e instanceof Error?e.message:'操作失败');setBusy(false);}};
 const count=data?.counts[filter]||0;
 return <section className="photo-admin ajm-panel photo-review-panel"><h2>需要人工检查的图片</h2><p>这些照片已去除水印，请检查车辆有没有被修坏。满意就选中并点击“确认可用”；不满意请选择“暂不使用”。其余照片自动处理，不用逐张操作。</p>
 {error&&<p role="alert" className="photo-error">{error}</p>}{notice&&<p role="status">{notice}</p>}
 <div className="photo-controls"><button disabled={busy||!data} onClick={()=>void run('control',{enabled:!data?.processingEnabled},data?.processingEnabled?'图片处理已暂停，正在处理的几张会先完成。':'已允许继续处理图片；Mac 开着且程序运行时会自动继续。')}>{data?.processingEnabled?'暂停图片处理':'继续图片处理'}</button><button disabled={busy} onClick={()=>void load()}>刷新待检查图片</button><span>暂停图片不会停止找车，也不会下架已有车辆。</span></div>
 {!!data?.items.length&&<div className="photo-controls"><span>待检查（{data?.counts.pending_review||0}）</span><select aria-label="每页数量" disabled={busy} value={size} onChange={e=>{setSize(Number(e.target.value));setOffset(0);}}>{[20,50,100].map(n=><option key={n} value={n}>每页 {n} 张</option>)}</select></div>}
 <div className="photo-grid">{data?.items.map(p=><article key={p.id}><label><input type="checkbox" checked={selected.has(p.id)} disabled={busy||!eligible(p)} onChange={()=>toggle(p.id)}/>{p.vehicle}</label><small>{labels[p.status]}</small><button className="photo-pair photo-preview" onClick={()=>setZoom(p)} aria-label={`对比 ${p.vehicle}`}><span>{p.candidate_url?<img loading="lazy" decoding="async" src={p.candidate_url} alt="待审核成品"/>:'暂无成品'}<small>{p.detection?.detected?'修补结果 · 点击对比原图':'疑似水印 · 点击检查原图'}</small></span></button>{p.error&&<p className="photo-error">{p.error}</p>}</article>)}</div>
 {!busy&&data?.items.length===0&&<p>目前没有需要人工检查的图片。其他照片会自动处理。</p>}
 {!!data?.items.length&&<div className="photo-controls"><button disabled={busy||offset===0} onClick={()=>setOffset(Math.max(0,offset-size))}>上一页</button><span>第 {offset/size+1} 页 · 共 {count} 张</span><button disabled={busy||offset+size>=count} onClick={()=>setOffset(offset+size)}>下一页</button></div>}
 {!!data?.items.length&&<div className="photo-bulk"><button disabled={busy} onClick={()=>setSelected(new Set(data?.items.filter(eligible).map(p=>p.id)))}>本页全选</button><button disabled={busy} onClick={()=>setSelected(new Set())}>取消全选</button><strong>已选 {selected.size} 张</strong><button disabled={busy||!chosen.length||chosen.some(p=>!p.candidate_url||!p.candidate_verified)} onClick={()=>{setDecision('approved');setAck(false);}}>确认可用</button><button disabled={busy||!chosen.length} onClick={()=>{setDecision('rejected');setAck(false);}}>暂不使用</button></div>}
 {zoom&&<div className="photo-overlay"><div role="dialog" aria-modal="true" aria-label="图片对比" className="photo-dialog"><button onClick={()=>setZoom(null)}>关闭</button><h2>{zoom.vehicle}</h2><div className="photo-pair">{zoom.original_url&&<img src={zoom.original_url} alt="原图"/>}{zoom.candidate_url&&<img src={zoom.candidate_url} alt="成品"/>}</div><div className="photo-controls"><button disabled={data?.items[0]?.id===zoom.id} onClick={()=>{const i=data!.items.findIndex(p=>p.id===zoom.id);setZoom(data!.items[i-1]);}}>上一张</button><button disabled={!eligible(zoom)||busy} onClick={()=>toggle(zoom.id)}>{selected.has(zoom.id)?'取消选择':'选择此图'}</button><button disabled={data?.items.at(-1)?.id===zoom.id} onClick={()=>{const i=data!.items.findIndex(p=>p.id===zoom.id);setZoom(data!.items[i+1]);}}>下一张</button></div></div></div>}
 {decision&&<div className="photo-overlay"><div role="dialog" aria-modal="true" aria-label="确认批量审核" className="photo-dialog small"><h2>{decision==='approved'?'确认可用':'暂不使用'} {selected.size} 张照片</h2><p>照片都处理完后，只要还有合格图片，车辆就能自动上架。自动重试 3 次仍失败的图片会跳过；手动选择“暂不使用”会阻止该车上架。</p><label><input type="checkbox" checked={ack} disabled={busy} onChange={e=>setAck(e.target.checked)}/>{decision==='approved'?'我已检查成品，确认无残留水印且未影响车辆信息，并确认可以公开展示。':'确认拒绝这些照片，并停止展示受影响的车辆。'}</label>{error&&<p role="alert">{error}</p>}<div className="photo-controls"><button disabled={busy} onClick={()=>setDecision(null)}>取消</button><button disabled={!ack||busy} onClick={()=>void run('decide-batch',{ids:[...selected],decision},'审核已保存，车辆上架状态已自动更新。')}>{busy?'正在保存…':'确认'}</button></div></div></div>}
 </section>;
}
