import { ArrowRight, Calculator, ExternalLink, HandCoins, ShieldCheck } from 'lucide-react';
import { useState } from 'react';
import { Link } from 'react-router';
import mtfAlbanyLogo from '../../data/pic/partner-mtf-albany.png';
import { useLanguage } from '../components/SiteTranslator';

const mtfAlbanyApplyUrl = 'https://apply.mtf.co.nz/?originatorid=2309&utm_source=Innogroup&utm_medium=introducer%20website&utm_campaign=Innogroup';

export function Finance() {
  const { text } = useLanguage();
  const [vehiclePrice, setVehiclePrice] = useState(30000);
  const [deposit, setDeposit] = useState(5000);
  const [term, setTerm] = useState(48);
  const principal = Math.max(0, vehiclePrice - deposit);
  const monthlyRate = 0.0799 / 12;
  const monthlyPayment = principal === 0 ? 0 : (principal * monthlyRate * Math.pow(1 + monthlyRate, term)) / (Math.pow(1 + monthlyRate, term) - 1);
  const weeklyPayment = monthlyPayment * 12 / 52;

  return (
    <div className="pt-20">
      <section className="bg-[#101113] px-4 py-20 text-white sm:py-28"><div className="section-shell grid gap-10 lg:grid-cols-[1.1fr_0.9fr] lg:items-center"><div className="max-w-3xl"><p className="text-xs font-bold uppercase tracking-[0.22em] text-primary">Vehicle Finance</p><h1 className="mt-6 text-white">{text({ en: 'Understand the weekly cost before you apply.', zh: '申请之前，先了解大概每周需要还多少。' })}</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-white/68">{text({ en: 'Estimate a possible repayment, then apply directly with MTF Albany or ask Inno to help you start the conversation.', zh: '先估算可能的还款金额，再直接向 MTF Albany 申请，或请 Inno 协助沟通。' })}</p></div><div className="flex min-h-56 items-center justify-center rounded-[24px] bg-white p-8"><img src={mtfAlbanyLogo} alt="MTF Albany" className="max-h-32 w-full object-contain" /></div></div></section>
      <section className="px-4 py-16 sm:py-24"><div className="section-shell grid gap-10 lg:grid-cols-[0.8fr_1.2fr] lg:items-start"><div><p className="section-kicker"><Calculator className="h-4 w-4"/>{text({ en: 'Repayment estimator', zh: '还款估算器' })}</p><h2 className="mt-5">{text({ en: 'Get a rough weekly figure.', zh: '先得到一个大概的每周金额。' })}</h2><p className="mt-5 leading-8">{text({ en: 'This example uses a 7.99% p.a. illustrative rate. Actual rate, fees, terms and approval depend on lender assessment.', zh: '此示例按 7.99% 年利率估算。实际利率、费用、期限与审批结果取决于贷款方评估。' })}</p></div><div className="rounded-[24px] border border-black/7 bg-white p-7 shadow-[0_18px_60px_rgba(0,0,0,0.07)] sm:p-10"><div className="space-y-7"><label className="block"><span className="flex justify-between font-bold"><span>{text({ en: 'Vehicle price', zh: '车辆价格' })}</span><span>${vehiclePrice.toLocaleString()}</span></span><input type="range" min="10000" max="100000" step="1000" value={vehiclePrice} onChange={(event) => { const next = Number(event.target.value); setVehiclePrice(next); setDeposit((current) => Math.min(current, next / 2)); }} className="mt-4 w-full accent-[#c7a24a]" /></label><label className="block"><span className="flex justify-between font-bold"><span>{text({ en: 'Deposit', zh: '首付' })}</span><span>${deposit.toLocaleString()}</span></span><input type="range" min="0" max={vehiclePrice / 2} step="500" value={deposit} onChange={(event) => setDeposit(Number(event.target.value))} className="mt-4 w-full accent-[#c7a24a]" /></label><div><p className="font-bold text-foreground">{text({ en: 'Term', zh: '贷款周期' })}</p><div className="mt-3 grid grid-cols-4 gap-2">{[24, 36, 48, 60].map((value) => <button key={value} type="button" onClick={() => setTerm(value)} className={`rounded-xl border px-3 py-3 text-sm ${term === value ? 'border-primary bg-primary text-white' : 'border-black/10 bg-white'}`}>{value}m</button>)}</div></div><div className="rounded-xl bg-[#111214] p-6 text-center text-white"><p className="text-sm text-white/55">{text({ en: 'Illustrative weekly payment', zh: '示例每周还款' })}</p><p className="mt-2 text-4xl font-bold text-white">${weeklyPayment.toFixed(2)}</p><p className="mt-3 text-xs text-white/45">{text({ en: 'Example only — not an offer of finance.', zh: '仅供示例参考，不构成贷款要约。' })}</p></div></div></div></div></section>
      <section className="border-t border-black/7 bg-white/55 px-4 py-16 sm:py-24"><div className="section-shell"><h2>{text({ en: 'Choose how you want to continue.', zh: '选择下一步申请方式。' })}</h2><div className="mt-9 grid gap-5 lg:grid-cols-2"><a href={mtfAlbanyApplyUrl} target="_blank" rel="noreferrer" className="group section-card p-7"><ShieldCheck className="h-7 w-7 text-primary"/><h3 className="mt-8">{text({ en: 'Apply Directly with MTF Albany', zh: '直接向 MTF Albany 申请' })}</h3><p className="mt-3">{text({ en: 'Continue on the lender’s application website.', zh: '前往贷款方网站继续申请。' })}</p><span className="mt-7 inline-flex items-center gap-2 font-bold">{text({ en: 'Open application', zh: '打开申请页面' })}<ExternalLink className="h-4 w-4"/></span></a><Link to="/contact?type=finance#quote" className="group section-card p-7"><HandCoins className="h-7 w-7 text-primary"/><h3 className="mt-8">{text({ en: 'Ask Inno for Finance Assistance', zh: '请 Inno 协助贷款沟通' })}</h3><p className="mt-3">{text({ en: 'Start with basic contact details and your vehicle budget.', zh: '先提供联系方式和车辆预算即可。' })}</p><span className="mt-7 inline-flex items-center gap-2 font-bold">{text({ en: 'Ask for assistance', zh: '请求协助' })}<ArrowRight className="h-4 w-4"/></span></Link></div></div></section>
    </div>
  );
}
